TestBack/TestBack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tree_menu.urls')),
    path('admin/', admin.site.urls),
]

TestBack/tree_menu/urls.py
from tree_menu.views import *
from django.urls import path

urlpatterns = [
    path('', menu, name='menu'),

    # Отображаем в адресной строке активные пункты меню
    path('<str:what_menu>/<str:planet>', menu, name='planet'),

]

TestBack/tree_menu/models.py
from django.db import models

# Create your models here.


class my_menu(models.Model):
     name_menu = models.CharField(max_length=30)
     name = models.CharField(max_length=30)
     description = models.TextField('Описание')

     class Meta:
         verbose_name = 'Меню'
         verbose_name_plural = 'Меню'

     def __str__(self):
         return self.name


class submenu(models.Model):
    parent = models.ForeignKey(my_menu, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=500)
    url_link = models.TextField(max_length=1000,  verbose_name='Внешний URL-адрес статьи',)
    selfparent = models.ForeignKey('self', on_delete=models.SET_DEFAULT, verbose_name='Вложить в', default=0, null=True, blank=True,)

    class Meta:
        verbose_name = 'Вложение меню'
        verbose_name_plural = 'Вложения меню'

    def __str__(self):
        return self.name

TestBack/tree_menu/views.py
from django.shortcuts import render


# Create your views here.
def menu(request, what_menu='', planet=''):
    if what_menu == '' and planet == '':
        return render(request, 'tree_menu/base.html')
    else:
        context = {'artilcle': 'Раздел: ' + what_menu + '</br>' + ' Статья про ' + planet}
        return render(request, 'article/article.html', context)

TestBack/tree_menu/templates/article/article.html
{% extends 'tree_menu/base.html' %}

{% block content %}

{% autoescape off %}
<h2>{{ artilcle }}</h2>
{% endautoescape %}
{% endblock %}

TestBack/tree_menu/templates/tags/d_menu.html
<ul class="tree-padding tree-vertical-lines tree-horizontal-lines tree-summaries tree-markers tree-buttons">
  <li>
    <details open>
      {% for key, value in m_menu.items %}
        {% if forloop.first %}
          <summary>{{ key }}</summary>
          <ul>
            {% for i in value %}
              <li>
                <details>
                  <summary>{{ i }}</summary>
                  <ul>
                    {% for p in i.submenu_set.all %}
                    <li><a href="{% url 'planet' key p %}">{{ p }}</a></li>
                    {% endfor %}
                  </ul>
                </details>
              </li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endfor %}
    </details>
  </li>
</ul>

TestBack/tree_menu/templates/tree_menu/base.html
{% load menu_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" href="{% static 'tree_menu/tree_menu.css' %}" rel="stylesheet"/>
    <title>Title</title>
</head>
<nav>{% draw_menu "main_menu" %} {% draw_menu "Stars" %}</nav>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>